SET C51INC=G:\Keil 4 C51\C51\INC\
SET C51LIB=G:\Keil 4 C51\C51\LIB
SET CPU_TYPE=STC12C5A60S2
SET CPU_VENDOR=STC12C5A16S2 Series
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x00B71B00
"G:\Keil 4 C51\C51\BIN\A51.EXE" @.\temp\STARTUP._ia
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\sem.__i
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\test.__i
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\uart.__i
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\12864.__i
"G:\Keil 4 C51\C51\BIN\A51.EXE" @.\temp\12864._ia
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\stcad.__i
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\xos.__i
"G:\Keil 4 C51\C51\BIN\A51.EXE" @.\temp\xos._ia
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\kernel.__i
"G:\Keil 4 C51\C51\BIN\A51.EXE" @.\temp\kernel._ia
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\xlib.__i
"G:\Keil 4 C51\C51\BIN\A51.EXE" @.\temp\xlib._ia
"G:\Keil 4 C51\C51\BIN\LX51.EXE" @.\temp\xos.lnp
