SET C51INC=G:\Keil 4 C51\C51\INC\
SET C51LIB=G:\Keil 4 C51\C51\LIB
SET CPU_TYPE=STC90C52RC
SET CPU_VENDOR=STC90C51RC Series
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x00A8C000
"G:\Keil 4 C51\C51\BIN\A51.EXE" @.\temp\STARTUP._ia
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\sem.__i
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\test.__i
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\kernel.__i
"G:\Keil 4 C51\C51\BIN\A51.EXE" @.\temp\kernel._ia
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\xos.__i
"G:\Keil 4 C51\C51\BIN\A51.EXE" @.\temp\xos._ia
"G:\Keil 4 C51\C51\BIN\C51.EXE" @.\temp\uart.__i
"G:\Keil 4 C51\C51\BIN\BL51.EXE" @.\temp\xos.lnp
"G:\Keil 4 C51\C51\BIN\OH51.EXE" ".\temp\xos" 
